version: "2"

services:

  gitannex:
    build: ./annex-service
    container_name: volume
    image: annex
    environment:
      NAME_OF_REPOS: "Main Repository"
      YOUR_NAME: "Anonymous User"
      YOUR_EMAIL: "qlb@tagurl.io"
      VIRTUAL_HOST: "vol.tagurl.io"
      LETSENCRYPT_EMAIL: "qlb@tagurl.io"
      LETSENCRYPT_HOST: "vol.tagurl.io"
    expose: 
      - "7000"
    volumes:
      - ./annex-service/repos:/repos
      - ./annex-service/ssh_keys:/ssh_keys
    restart: always

networks:
  default:
    external:
      name: nginx_default
