#!/bin/bash


mkdir -p "$LOCATION_OF_REPOS"
# Initialize Git (if needed)
if [ ! -f "${LOCATION_OF_REPOS}/.git" ]; then
    echo "NO GIT REPO FOUND... CREATING"
    git -C "$LOCATION_OF_REPOS" init
    git -C "$LOCATION_OF_REPOS" config user.email "$YOUR_EMAIL"
    git -C "$LOCATION_OF_REPOS" config user.name "$YOUR_NAME"
fi

# Initialize Git Annex (if needed)
if [ ! -f "${LOCATION_OF_REPOS}/.git/annex" ]; then
    echo "GIT REPO EXISTS HOWEVER NO ANNEX... CREATING"
    git -C "$LOCATION_OF_REPOS" annex init "$NAME_OF_REPOS"
fi

echo "STARTING GIT ANNEX..."
echo git -C "$LOCATION_OF_REPOS" annex webapp
