#!/bin/bash


mkdir -p "$LOCATION_OF_REPOS"
# Initialize Git (if needed)
if [ ! -f "${LOCATION_OF_REPOS}/.git" ]; then
    echo "NO GIT REPO FOUND... CREATING"
    git -C "$LOCATION_OF_REPOS" init
    git -C "$LOCATION_OF_REPOS" config user.email "$YOUR_EMAIL"
    git -C "$LOCATION_OF_REPOS" config user.name "$YOUR_NAME"
fi

# Initialize Git Annex (if needed)
if [ ! -f "${LOCATION_OF_REPOS}/.git/annex" ]; then
    echo "NO GIT REPO EXISTS HOWEVER NO ANNEX... CREATING"
    git -C "$LOCATION_OF_REPOS" annex init "$NAME_OF_REPOS"
fi

PRIVATE_SSH_KEY=$(ls /ssh_keys/id_?sa)
if [ -z "$PRIVATE_SSH_KEY" ]; then
    echo "NO SSH KEYS FOUND... IF DESIRED PLACE IN VOLUME /ssh_keys with name matching id_?sa"
else
    echo "SSH_KEYS_FOUND $PRIVATE_SSH_KEY"
    mkdir -p $HOME/.ssh
    ln -s $PRIVATE_SSH_KEY $HOME/.ssh/
fi

echo "STARTING GIT ANNEX..."
git -C "$LOCATION_OF_REPOS" annex webapp
