#!/bin/bash

# Check parameters
if [ "$#" -ne 4 ]; then
    echo $#
    echo "USAGE: boot [LOCATION_OF_REPOS] [NAME_OF_REPOS] [YOUR_NAME] [YOUR_EMAIL]"
    exit 1
fi

LOCATION_OF_REPOS="$1"
NAME_OF_REPOS="$2"
YOUR_NAME="$3"
YOUR_EMAIL="$4"

# Initialize Git (if needed)
if [ ! -f "${LOCATION_OF_REPOS}/.git" ]; then
    echo "NO GIT REPO FOUND... CREATING"
    git -C "$LOCATION_OF_REPOS" init
    git -C "$LOCATION_OF_REPOS" config user.email "$YOUR_EMAIL"
    git -C "$LOCATION_OF_REPOS" config user.name "$YOUR_NAME"
fi

# Initialize Git Annex (if needed)
if [ ! -f "${LOCATION_OF_REPOS}/.git/annex" ]; then
    echo "GIT REPO EXISTS HOWEVER NO ANNEX... CREATING"
    git -C "$LOCATION_OF_REPOS" annex init "$NAME_OF_REPOS"
fi

echo "STARTING GIT ANNEX..."
git -C "$LOCATION_OF_REPOS" annex webapp
