#!/bin/bash

/annex-boot/annex &
PID1=$!
$(sleep 3 && ./annex-boot/proxy "$1" "$5") &
PID2=$!
COUNT=2
while [ $COUNT -eq 2 ]; do
    COUNT=$(jobs | grep Running | wc -l)
    echo "COUNT $COUNT"
    sleep 1
done
