#!/bin/bash

REPO_DIR=$1
PORT=$5

URL=$(cat $REPO_DIR/.git/annex/webapp.html  | grep '^<meta.* URL' | sed 's/.* URL=//' | sed 's/".*//')
PORT=$(echo $URL | sed 's/.*\://' | sed 's/\/.*//');
AUTH=$(echo $URL | sed 's/.*=//' );

cat /annex-boot/nginx.conf.tpl | sed "s/\\[PORT\\]/$PORT/" | sed "s/\\[AUTH\\]/$AUTH/" > /annex-boot/nginx.conf
nginx -p . -c /annex-boot/nginx.conf
